---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 陈亮.
--- DateTime: 2023/5/22 15:31
---

--1参数
--1.1优惠卷id
local voucherId=ARGV[1]
--1.2用户id
local userId=ARGV[2]
--1.3 订单id
local orderId=ARGV[3]

--2数据key
--2.1库存key
local stockkey='seckill:stock:'..voucherId
--2.2订单key
local orderKey='seckill:order:'..voucherId

--3脚本业务
--3.1判断库存是否充足
if(tonumber(redis.call('get',stockkey))<=0) then
    --库存不足，返回1
    return 1
end
--3.2判断用户是否下过单
if(redis.call('sismember',orderKey,userId)==1)then
    --3.3下过单，说明重复下单，返回2
    return 2
end
--3.4 扣库存
redis.call('incrby',stockkey,-1)
--3.5 下单（保存用户）
redis.call('sadd',orderKey,userId)
--3.6 发送消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0

