---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 陈亮.
--- DateTime: 2023/5/20 20:35
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0